default: false

# Tags
spelling: true
indentation: false
links: true
whitespace: true
html: true

# Individual tweaks
MD010:
  code_blocks: false # Disallow hard tabs except in code blocks.
MD028: false # Allow blank lines between blockquotes.
