{{- define "common.service" -}}
{{- $common := dict "Values" .Values.common -}} 
{{- $noCommon := omit .Values "common" -}} 
{{- $overrides := dict "Values" $noCommon -}} 
{{- $noValues := omit . "Values" -}} 
{{- with merge $noValues $overrides $common -}}
{{- if .Values.configyaml }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: zqd-conf
data:
  zqd-config.yaml: |
    logger:
      type: waterfall
      children:
      - name: http.access
        level: info
        path: /Users/mark/oss/brim/run/logs/zqd-access.log
        mode: rotate
      - level: info
        path: /Users/mark/oss/brim/run/logs/zqd-core.log
        mode: rotate
{{- end }}
