apiVersion: v2
name: redis
description: A Helm chart for redis
type: application
version: 0.1.0
appVersion: 0.1.0

dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x

