# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

# Go Docker environment
executors:
  go_builder:
    docker:
      - image: circleci/golang:1.13-buster

commands:
  log_date:
    description: Log date
    steps:
      - run:
          name: Log date
          command: date -u

jobs:
  build:
    executor: go_builder
    steps:
      - log_date
      - checkout
      - run: go mod download
      - run:
          name: Go vet
          command: 'make vet'
      - run:
          name: Go fmt
          command: 'make fmt'
      - run:
          name: Unit Tests
          command: 'make test-unit'
      - run:
          name: Build
          command: 'make build'
      - run:
          name: System Tests
          command: 'make test-system'
      - run:
          name: Heavy Tests
          command: 'make test-heavy'

workflows:
  version: 2
  main:
    jobs:
      - build
