script: zq -i ndjson -f tzng -j types.json "*" in.ndjson

inputs:
  - name: in.ndjson
    data: |
      {"_path":"simple", "number": 4}
  - name: types.json
    data: |
        {
          "descriptors": {
            "simple_log": [
              {
                "name": "_path",
                "type": "string"
              },
              {
                "name": "number",
                "type": "nosuchtype"
              }
            ]
          },
          "rules": [
            {
            "descriptor": "simple_log",
              "name": "_path",
              "value": "simple"
            }
          ]
        }


outputs:
  - name: stderr
    regexp: |
      unknown type: nosuchtype
