# Configuration file used for creating a development cluster with eksctl
# Schema reference:
# https://eksctl.io/usage/schema/
# Doc reference:
# https://eksctl.io/usage/creating-and-managing-clusters/
# Doc for Managed NodeGroups:
# https://eksctl.io/usage/eks-managed-nodes/

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: zq-dev
  region: us-east-2
  version: "1.17"
  tags:
    cluster: zq-dev

managedNodeGroups:
  - name: standard-workers
    instanceType: t3.large
    minSize: 1
    maxSize: 3
    desiredCapacity: 1
    ssh:
      allow: false
    iam:
      attachPolicyARNs:
        # Policies genrically required for EKS nodes
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        # S3 access policies needed for zqd
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      withAddonPolicies:
        autoScaler: true

