script: |
  source service.sh
  super db create -q -db $DB_PATH test
  super db ls
  echo ===
  super db drop -q -db $DB_PATH -f test
  super db ls

inputs:
  - name: service.sh
    source: service.sh

outputs:
  - name: stdout
    regexp: |
      test \w{27} key ts order desc
      ===
  - name: stderr
    data: ""
