script: |
  source service.sh
  zed create -q -lake $LAKE_PATH test
  zed ls
  echo ===
  zed drop -q -lake $LAKE_PATH -f test
  zed ls

inputs:
  - name: service.sh
    source: service.sh

outputs:
  - name: stdout
    regexp: |
      test \w{27} key ts order desc
      ===
  - name: stderr
    data: ""
