postgres:
  addr: zsrv-postgresql:5432
  username: "zqd"
  database: "zqd"
  # passwordSecretName must have a value called postgres-password
  passwordSecretName: "postgres"
recruiter:
  replicaCount: 1
root:
  datauri: "file:///spaces"
  recruiterAddr: zsrv-recruiter:9867
worker:
  recruiterAddr: zsrv-recruiter:9867

global:
  AWSRegion: ""
  image:
    repository: "localhost:5000/"
    pullPolicy: Always
    tag: "zqd"
  imagePullSecrets: []
  useCredSecret: false
