spq: |
  values
    "foo"::enum(foo,bar),
    "bar"::enum("foo","bar"),
    "fu bar"::enum("foo","bar","fu bar"),
    "fu bar"::enum("foo","bar",`fu bar`),
    "fu bar"::enum("foo", "bar", `fu bar`),
    "hello"::enum("foo","bar"),
    1::enum("foo","bar"),
    {x:1,s:"foo"}::enum("foo","bar"),
    {x:1,s:"foo"}.s::enum("foo","bar"),
    "HEADS"::(flip=(enum(HEADS,TAILS))),
    {head:"HEADS"::(flip=enum(HEADS,TAILS))},
    <enum(a,b)>==<enum(a,b)>,
    <enum(a,b)>==<enum(b,c)>,
    <enum(a,b)>==<enum(a,b,c)>

input: |
  null

output: |
  "foo"::enum(foo,bar)
  "bar"::enum(foo,bar)
  "fu bar"::enum(foo,bar,"fu bar")
  "fu bar"::enum(foo,bar,"fu bar")
  "fu bar"::enum(foo,bar,"fu bar")
  error({message:"no such symbol in enum(foo,bar)",on:"hello"})
  error({message:"cannot cast to enum",on:1})
  error({message:"cannot cast to enum",on:{x:1,s:"foo"}})
  "foo"::enum(foo,bar)
  "HEADS"::(flip=enum(HEADS,TAILS))
  {head:"HEADS"::(flip=enum(HEADS,TAILS))}
  true
  false
  false
