script: |
  export ZED_LAKE=test
  zed init -q
  zed create -q test1
  zed create -q test2
  zed create -q test3
  zed branch -use test2 -q live
  zed manage -config=inherit.yaml -log.path=inherit.log
  zq -Z 'msg == "updating pool" | cut name, branch, interval | sort name' inherit.log > inherit.zson

inputs:
  - name: inherit.yaml
    data: |
      interval: 1s
      pools:
        - pool: test1
          interval: 5s
        - pool: test2
          branch: "live"

outputs:
  - name: inherit.zson
    data: | 
      {
          name: "test1",
          branch: "main",
          interval: 5
      }
      {
          name: "test2",
          branch: "live",
          interval: 1
      }
      {
          name: "test3",
          branch: "main",
          interval: 1
      }
  - name: stderr
    data: ""
  - name: stdout
    data: ""
