name: "Deploy"

on:
  push:
    branches:
      - master
      - deploy-job-1

jobs:
  ecr-image-push:
    # Build and push a Docker image for zqd.
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          export ZQD_ECR_HOST=${{ secrets.AWS_ECR_HOST }}
          make docker-push-ecr

  eks-deploy-test:
    # Run smoke tests for zqd image prior to deploying to ci-master.
    needs: ecr-image-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          set -x
          NAMESPACE=ci-${{ github.run_number }}
          SPACE=files
          export ZQD_DATA_URI=s3://zq-ci-test/$(date +%y-%m-%d).${{ github.run_number }}
          export ZQD_ECR_HOST=${{ secrets.AWS_ECR_HOST }}
          make install
          mkdir testlog         
          aws s3 rm --recursive $ZQD_DATA_URI || : # clear data from previous run
          aws eks --region us-east-2 update-kubeconfig --name zq-test
          #
          # Create temporary namespace for tests and deploy zsvc
          #     
          kubectl create ns $NAMESPACE || :
          kubectl config set-context --current --namespace=$NAMESPACE
          helm uninstall zsrv || :
          k8s/postgres-secret.sh || :
          make helm-install PG_PERSIST=false
          kubectl wait --for=condition=Ready --timeout=60s pods/zsrv-postgresql-0
          kubectl wait --for=condition=available --timeout=120s deployment/zsrv-recruiter
          kubectl wait --for=condition=available --timeout=120s deployment/zsrv-root
          kubectl wait --for=condition=available --timeout=120s deployment/zsrv-worker
          #
          # Scale cluster for tests and set up port-forwards,
          # then wait for the forwarded ports to be available.
          #
          kubectl scale --replicas=4 deployment/zsrv-worker
          kubectl port-forward svc/zsrv-recruiter 8020:9867 &
          kubectl port-forward svc/zsrv-root 9867:9867 &
          for i in {1..5} ; do
            if nc -z localhost 8020 </dev/null ; then
              break
            fi
            sleep 1
          done
          for i in {1..5} ; do
            if nc -z localhost 9867 </dev/null ; then
              break
            fi
            sleep 1
          done
          #
          # Create archive for tests
          #
          time zapi ls
          time zapi new -k archivestore -d $ZQD_DATA_URI $SPACE
          # Post an archive of about 1.6 GB to run test queries.
          time zapi -s $SPACE postpath s3://brim-sampledata/wrccdc/zeek-logs/files.log.gz
          [[ 4 == $(curl http://localhost:8020/recruiter/listfree | jq -r ".workers | length") ]]
          #
          # Run cluster tests
          #
          make test-cluster
      - name: Get zqd logs and remove namespace on success or failure
        if: ${{ always() }}
        run: |
          set -x
          ZQD_DATA_URI=s3://zq-ci-test/$(date +%y-%m-%d).${{ github.run_number }}
          kubectl logs --tail -1 -l app.kubernetes.io/name=recruiter > testlog/recruiter.log
          kubectl logs --tail -1 -l app.kubernetes.io/name=root > testlog/root.log
          kubectl logs --tail -1 -l app.kubernetes.io/name=worker > testlog/worker.log
          kubectl delete ns ci-${{ github.run_number }}
      - name: Save logs as artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: eks-testlog
          path: testlog/

  eks-master-deploy:
    # Deploys this build to ci-master namespace so it will be available
    # for manual testing. Only deploy if previous jobs succeed.
    needs: eks-deploy-test
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          set -x
          export ZQD_DATA_URI=s3://zq-ci-master/manual-test
          export ZQD_ECR_HOST=${{ secrets.AWS_ECR_HOST }}
          aws eks --region us-east-2 update-kubeconfig --name zq-test
          kubectl create ns ci-master || :
          kubectl config set-context --current --namespace=ci-master
          helm uninstall zsrv || :
          make helm-install
