name: "Deploy"

on:
  push:
    branches:
      - master
      - eks-test-2
  workflow_dispatch:
     inputs:
       namespace:
         description: 'K8s namespace'
         default: 'ci-master'     
       s3data:
         description: 'S3 data directory'
         default: 's3://zq-ci-master/manual-test'
jobs:
  ecr-image-push:
    # Build and push a Docker image for zqd.
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - env:
          ZQD_ECR_HOST: ${{ secrets.AWS_ECR_HOST }}
        run: |
          make docker-push-ecr
  eks-test-deploy:
    # Deploys this build to a temporary namespace in order to run smoke tests.
    needs: ecr-image-push
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set current date as env variable $TODAY
        run: echo "TODAY=$(date +'%y-%m-%d')" >> $GITHUB_ENV
      - env:
          CLUSTER: zq-test
          NAMESPACE: ci-${{ github.run_number }}
          ZQD_ECR_HOST: ${{ secrets.AWS_ECR_HOST }}
          ZQD_DATA_URI: s3://zq-ci-test/${{ env.TODAY }}.${{ github.run_number }}
        run: |
          set -x
          aws eks --region us-east-2 update-kubeconfig --name $CLUSTER
          kubectl create ns $NAMESPACE || :
          kubectl config set-context --current --namespace=$NAMESPACE
          make helm-uninstall
          make helm-install-recruiter
          make helm-install-root
          make helm-install-worker
  eks-test-zapi-1:
    # Run smoke tests for zqd image prior to deploying to ci-master.
    needs: eks-test-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set current date as env variable
        run: echo "TODAY=$(date +'%y-%m-%d')" >> $GITHUB_ENV
      - env:
          CLUSTER: zq-test
          NAMESPACE: ci-${{ github.run_number }}
          SOURCE_LOG_1: s3://brim-sampledata/wrccdc/zeek-logs/files.log.gz
          SPACE: files
          ZQD_DATA_URI: s3://zq-ci-test/${{ env.TODAY }}.${{ github.run_number }}
        run: |
          set -x
          make install
          aws eks --region us-east-2 update-kubeconfig --name $CLUSTER
          kubectl config set-context --current --namespace=$NAMESPACE
          kubectl scale --replicas=4 deployment/worker-zqd
          kubectl port-forward svc/recruiter-zqd 8020:9867 &
          kubectl port-forward svc/root-zqd 9867:9867 &
          sleep 2 # wait for port-forwards to complete
          time zapi ls
          time zapi new -k archivestore -d $ZQD_DATA_URI $SPACE
          # Post an archive of about 1.6 GB to run test queries.
          time zapi -s $SPACE post $SOURCE_LOG_1
          # There should be 4 workers running now.
          [[ 4 == $(curl http://localhost:8020/recruiter/listfree | jq -r ".workers" | jq length) ]]     
          time zapi -s $SPACE get -workers 1 -t '"FgzbkQ15TOoOENn1lb" | sort tx_hosts'
          time zapi -s $SPACE get -workers 2 -t '"FgzbkQ15TOoOENn1lb" | sort tx_hosts'
          time zapi -s $SPACE get -workers 4 -t '"FgzbkQ15TOoOENn1lb" | sort tx_hosts'
          time zapi -s $SPACE get -workers 4 -t 'count()' > count.tzng
          time zapi -s $SPACE get -workers 4 -t \
            '* | count() by tx_hosts | sort -r count | head 5' > countbytxhost.tzng
          diff count.tzng k8s/testdiff/count.tzng
          diff countbytxhost.tzng k8s/testdiff/countbytxhost.tzng
      - name: Cleanup on success or failure
        if: ${{ always() }}
        env:
          NAMESPACE: ci-${{ github.run_number }}
        run: kubectl delete ns $NAMESPACE
  eks-master-deploy:
    # Deploys this build to ci-master namespace so it will be available
    # for manual testing. Only deploy if previous jobs succeed.
    needs: eks-test-zapi-1
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - env:
          CLUSTER: zq-test
          NAMESPACE: ${{ github.event.inputs.namespace }}
          ZQD_ECR_HOST: ${{ secrets.AWS_ECR_HOST }}
          ZQD_DATA_URI: ${{ github.event.inputs.s3data }}
        run: |
          set -x
          aws eks --region us-east-2 update-kubeconfig --name $CLUSTER
          kubectl create ns $NAMESPACE || :
          kubectl config set-context --current --namespace=$NAMESPACE
          make helm-uninstall
          make helm-install-recruiter
          make helm-install-root
          make helm-install-worker
