name: "Tests"

on:
  # pull_request:
  push:
    branches:
      k8s-makefile-rules
      #- master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - uses: actions/checkout@v1
      - run: go mod download
      - run: make fmt
      - run: make tidy
      - run: |
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:oisf/suricata-stable
          sudo apt-get update
          sudo apt-get install -y suricata
      - run: make vet
      - run: make test-generate
      - run: make test-unit
      - run: make test-system
      - run: make test-zeek
      - run: make test-heavy
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - uses: actions/checkout@v1
      - run: go test -short ./...
      - run: mkdir dist -ea 0
      - run: go build -o dist ./cmd/...
      - run: go test -v ./tests
      - run: make test-zeek
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
  zng-output-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - uses: actions/checkout@v1
      - run: make install
      - run: make zng-output-check
  ecr-image-push:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: make docker-push-ecr
  eks-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - env:
          ZQD_ECR_HOST: ${{ secrets.AWS_ECR_HOST }
          ZQD_DATA_URI: s3://zqd-demo-1/mark/zqd-meta
          ZQD_K8S_USER: ci-master
          ZQD_TEST_CLUSTER: zq-test.us-east-2.eksctl.io
      - run: aws eks --region us-east-2 update-kubeconfig --name zq-test
      - run: kubectl config set-context --current --namespace=ci-master
      - run: make helm-install
