name: "Tests"

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - uses: actions/checkout@v1
      - run: go mod download
      - run: make fmt
      - run: make tidy
      - run: |
          sudo apt-get update
          sudo apt-get install -y zip libnet1 libjansson4
      - run: make vet
      - run: make test-generate
      - run: make test-unit
      - run: make test-system
      - run: make test-pcapingest
      - run: make test-heavy
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - uses: actions/checkout@v1
      - run: go mod download
      - run: make test-unit
        shell: bash
      - run: make test-system
        shell: bash
      - run: make test-zeek
        shell: bash
      - run: make test-heavy
        shell: bash
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
  zng-output-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - uses: actions/checkout@v1
      - run: make install
      - run: make zng-output-check
  
