name: "Tests"

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - uses: actions/checkout@v1
      - run: go mod download
      - run: make fmt
      - run: make tidy
      - run: make vet
      - run: make test-generate
      - run: make test-unit
      - run: make test-system
      - run: make test-pcapingest
      - run: make test-heavy
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - uses: actions/checkout@v1
      - run: go test -short ./...
      - run: mkdir dist -ea 0
      - run: go build -o dist ./cmd/...
      - run: go test -v ./tests
      - run: make test-pcapingest
  z-output-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - uses: actions/checkout@v1
      - run: make install
      - run: make z-output-check
  test-services:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-retries 5
          --health-timeout 5s
        ports:
          - 5432:5432
      redis:
        image: redis:6
        ports:
          - "6379:6379"
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - uses: actions/checkout@v1
      - run: make test-services
