name: "Tests"

on:
  merge_group:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - run: |
          while true; do
            make TEST=TestZed/runtime/sam/op/merge/ztests/fork-merge
          done
