name: "Tests"

on:
  merge_group:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: c9cf7f1535cb4c907c9ec70cc6b17d62a38cb9d2
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - run: |
          NUM=1
          while true; do
            echo "Test iteration ${NUM}:"
            go test -short ./...
            NUM=$(expr $NUM + 1)
          done
        shell: sh
