name: "Tests"

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - uses: actions/checkout@v1
      - run: go mod download
      - run: make fmt
      - run: make tidy
      - run: |
          sudo apt-get update
          sudo apt-get install -y zip libnet1 libjansson4
      - run: make vet
      - run: make test-generate
      - run: make test-unit
      - run: make test-system
