name: Notify Brim

on:
  pull_request:
    types: closed

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Populate "merged" variable
      run: |
        merged=$(cat $GITHUB_EVENT_PATH | jq '.pull_request.merged')
        echo "::set-output name=merged::$merged"
      id: vars
    - name: Post PR closed event, if the close was a merge
      if: steps.vars.outputs.merged == 'true'
      run: |
        cat $GITHUB_EVENT_PATH
        cat $GITHUB_EVENT_PATH | jq '.pull_request | { "event_type": "zq-pr-merged", "client_payload": {body, "branch": .head.ref, merge_commit_sha, number, title, "url": .html_url, "user": .user.login}}' > payload.json
        curl -XPOST -u "${{ secrets.PAT_USERNAME }}:${{ secrets.PAT_TOKEN }}" -H "Accept: application/vnd.github.v3+json"  -H "Content-Type: application/json" ${{ secrets.MERGE_EVENT_URL }} --data @payload.json
