name: Perf check

on:
  push:
    branches:
      - rc-v*
  schedule:
    - cron: '5 8 * * *'
  workflow_dispatch:

jobs:
  perf-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run the perf testing script
      run: make perf-compare
    - name: Notify Brim HQ of failure
      uses: tiloio/slack-webhook-action@v1.1.2
      if: ${{ failure() }}
      with:
        slack_web_hook_url: ${{ secrets.SLACK_WEBHOOK_BRIMLABS_TEST }}
        slack_json: |
            {
              "username": "github-actions",
              "text": "Workflow \"${{ github.event.workflow_run.name }}\" failed on main.\n${{ github.event.workflow_run.html_url }}"
            }  
