name: Perf check

on:
  push:
    branches:
      - rc-v*
  schedule:
    - cron: '5 8 * * *'
  workflow_dispatch:

jobs:
  perf-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - uses: actions/checkout@v2
    - name: Add zeek-cut
      run: |
        echo 'deb http://download.opensuse.org/repositories/security:/zeek/xUbuntu_18.04/ /' | sudo tee /etc/apt/sources.list.d/security:zeek.list
        curl -fsSL https://download.opensuse.org/repositories/security:zeek/xUbuntu_18.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/security:zeek.gpg > /dev/null
        sudo apt update
        sudo apt -y install zeek
    - name: Run the perf testing script
      run: PATH="$(pwd)/dist:/opt/zeek/bin:$PATH" make perf-compare
    - name: Notify Brim HQ of failure
      uses: tiloio/slack-webhook-action@v1.1.2
      if: ${{ failure() }}
      with:
        slack_web_hook_url: ${{ secrets.SLACK_WEBHOOK_BRIMLABS_TEST }}
        slack_json: |
            {
              "username": "github-actions",
              "text": "Perf check failed: https://github.com/{{GITHUB_REPOSITORY}}/actions/runs/{{GITHUB_RUN_ID}}"
            }  
