name: release assets
on:
  push:
    tags:
      - v*
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.18'
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: go mod download
    - run: make fmt
    - run: make tidy
    - run: make vet
    - run: make test-generate
    - run: make test-unit
    - run: make test-system
    - run: make test-heavy
    - uses: goreleaser/goreleaser-action@v2
      with:
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
