name: release assets
on:
  push:
    tags:
      - v*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.14'
    - uses: actions/checkout@v1
    - run: make test-unit
    - run: make test-system
    - run: make test-zeek
    - run: make create-release-assets
    - name: upload release assets
      uses: svenstaro/upload-release-action@1.1.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: dist/release/*
        file_glob: true
        overwrite: true
