name: "Run sqllogictests"

on:
  pull_request:
    branches:
      - main
    types: closed
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch name, tag, or commit SHA to test'
        required: true
        default: 'main'
        type: string

jobs:
  test-sqllogic:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-22.04
    steps:
      - id: checkout-ref
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "ref=${{ github.event.inputs.ref }}" >> $GITHUB_OUTPUT
          else
            echo "ref=${{ github.event.pull_request.merge_commit_sha }}" >> $GITHUB_OUTPUT
          fi
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.checkout-ref.outputs.ref }}
          fetch-depth: 0    
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: make test-sqllogic
