name: "windows-testing"

on:
  push:
    branches:
      - "windows-testing"

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - uses: actions/checkout@v1
      - run: go test -short ./...
      - run: go test -v -tags=system ./tests
